#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
# run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".tool-versions" ] && [ "$(uname -s)" = "Darwin" ]; then
  echo "==> Installing package versions…"
  brew bootstrap-asdf
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check >/dev/null 2>&1  || {
    bundle install --quiet --without production
  }
fi

if [ -f "package.json" ]; then
  if ! command -v yarn >/dev/null; then
    echo "==> Installing yarn…"
    npm install -g yarn
  fi

  echo "==> Installing node packages…"
  yarn
fi
